# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files and tsconfig for build
COPY package.json package-lock.json tsconfig.json ./

# Install dependencies including devDependencies for build
RUN npm install

# Copy source code
COPY . .

# Build TypeScript
RUN npm run build

# Remove devDependencies
RUN npm prune --production

# Set environment to production
ENV NODE_ENV=production

# Expose no port (stdio)

# Start the server
CMD ["node", "dist/server.js"]
